agent.sources = spool_source
agent.channels = mem_channel
agent.sinks = hdfs_sink

# Source
agent.sources.spool_source.type = spooldir
agent.sources.spool_source.spoolDir = /home/maria_dev/vkospi-project/data
agent.sources.spool_source.fileSuffix = .COMPLETED
agent.sources.spool_source.ignorePattern = ^(.)*\\.zip$
# :      
agent.sources.spool_source.batchSize = 1000

# Channel (Memory Limit Extended)
agent.channels.mem_channel.type = memory
agent.channels.mem_channel.capacity = 1000000
agent.channels.mem_channel.transactionCapacity = 10000

# Sink
agent.sinks.hdfs_sink.type = hdfs
agent.sinks.hdfs_sink.hdfs.path = hdfs://sandbox-hdp.hortonworks.com:8020/user/maria_dev/raw_data/gdelt
agent.sinks.hdfs_sink.hdfs.fileType = DataStream
agent.sinks.hdfs_sink.hdfs.writeFormat = Text
# : 120   (120), 128MB   (134217728)
agent.sinks.hdfs_sink.hdfs.rollInterval = 120
agent.sinks.hdfs_sink.hdfs.rollSize = 134217728
agent.sinks.hdfs_sink.hdfs.rollCount = 0
agent.sinks.hdfs_sink.hdfs.idleTimeout = 60
agent.sinks.hdfs_sink.hdfs.filePrefix = events

# Bind
agent.sources.spool_source.channels = mem_channel
agent.sinks.hdfs_sink.channel = mem_channel
