me: Spark Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark pandas finance-datareader flake8

    - name: Syntax & Error Check
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
